// Authentic Menus for Srm : College Bites: Local Home Kitchen & Clg Bites Biryani Nation

export const DEFAULT_RESTAURANTS = [
  {
    id: "local-home-kitchen",
    name: "Local Home Kitchen",
    description: "Trust it, Taste it — Fast Food & Biryani's. Beside Ayyappa PG Hostel, Neerukonda.",
    cuisine: "Fast Food & Biryani's",
    location: "Beside Ayyappa PG Hostel - Neerukonda",
    phone: "9989955833",
    rating: 4.8,
    prep_time: "15-20 min",
    image_url: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=1200&q=80",
    is_open: true
  },
  {
    id: "clg-bites-biryani-nation",
    name: "Clg Bites Biryani Nation",
    description: "A Taste You'll Love... Fresh, Delicious Biryanis with Special Campus Discounts!",
    cuisine: "Chicken & Veg Biryanis",
    location: "Neerukonda Campus Hub, SRM University AP",
    phone: "9989955833",
    rating: 4.9,
    prep_time: "15-25 min",
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=1200&q=80",
    is_open: true
  },
  {
    id: "vilasa-cafe",
    name: "Vilasa Café",
    description: "High on life! Taste • Talks • Time — Fresh Biryanis, Starters, Chinese & Curries.",
    cuisine: "Biryani, Starters & Chinese",
    location: "Opp SRM University, E12 Road • Neerukonda, Amaravathi",
    phone: "9989955833",
    rating: 4.8,
    prep_time: "15-20 min",
    image_url: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80",
    is_open: true
  }
];

export const DEFAULT_MENU_ITEMS = [
  // =========================================================================
  // 1. CLG BITES BIRYANI NATION (Biryani Special Menu with Single & Full sizes)
  // =========================================================================

  // Chicken Biryani
  {
    id: "cbn-chk-dum-s",
    restaurant_id: "clg-bites-biryani-nation",
    restaurant_name: "Clg Bites Biryani Nation",
    category: "Chicken Biryani",
    name: "Chicken Dum Biryani (Single)",
    description: "Authentic slow-cooked dum biryani with marinated tender chicken and fragrant basmati rice.",
    price: 190,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "cbn-chk-dum-f",
    restaurant_id: "clg-bites-biryani-nation",
    restaurant_name: "Clg Bites Biryani Nation",
    category: "Chicken Biryani",
    name: "Chicken Dum Biryani (Full)",
    description: "Full portion aromatic Hyderabadi dum biryani with juicy chicken pieces, boiled egg & mirchi ka salan.",
    price: 260,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "cbn-chk-fry-s",
    restaurant_id: "clg-bites-biryani-nation",
    restaurant_name: "Clg Bites Biryani Nation",
    category: "Chicken Biryani",
    name: "Chicken Fry Biryani (Single)",
    description: "Crispy Andhra spiced chicken fry served generously over flavorful dum biryani rice.",
    price: 200,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "cbn-chk-fry-f",
    restaurant_id: "clg-bites-biryani-nation",
    restaurant_name: "Clg Bites Biryani Nation",
    category: "Chicken Biryani",
    name: "Chicken Fry Biryani (Full)",
    description: "Large serving of spicy roasted chicken fry pieces over seasoned ghee biryani rice.",
    price: 270,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "cbn-chk-bone-s",
    restaurant_id: "clg-bites-biryani-nation",
    restaurant_name: "Clg Bites Biryani Nation",
    category: "Chicken Biryani",
    name: "Chicken Boneless Biryani (Single)",
    description: "Tender, succulent boneless chicken cubes tossed in rich spices layered with fragrant biryani.",
    price: 210,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "cbn-chk-bone-f",
    restaurant_id: "clg-bites-biryani-nation",
    restaurant_name: "Clg Bites Biryani Nation",
    category: "Chicken Biryani",
    name: "Chicken Boneless Biryani (Full)",
    description: "Full generous portion of boneless chicken bites with spicy caramelized onion biryani rice.",
    price: 290,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "cbn-chk-lol-s",
    restaurant_id: "clg-bites-biryani-nation",
    restaurant_name: "Clg Bites Biryani Nation",
    category: "Chicken Biryani",
    name: "Chicken Lollipop Biryani (Single)",
    description: "Crisp seasoned chicken lollipops paired with hot dum biryani rice and raita.",
    price: 210,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "cbn-chk-lol-f",
    restaurant_id: "clg-bites-biryani-nation",
    restaurant_name: "Clg Bites Biryani Nation",
    category: "Chicken Biryani",
    name: "Chicken Lollipop Biryani (Full)",
    description: "Family size aromatic biryani crowned with multiple spicy chicken lollipops.",
    price: 290,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "cbn-chk-mogh-s",
    restaurant_id: "clg-bites-biryani-nation",
    restaurant_name: "Clg Bites Biryani Nation",
    category: "Chicken Biryani",
    name: "Chicken Moghalai Biryani (Single)",
    description: "Royal Mughlai style biryani cooked with rich egg gravy, cashew nut paste and tender chicken.",
    price: 220,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1642821373181-696a54913e9a?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "cbn-chk-mogh-f",
    restaurant_id: "clg-bites-biryani-nation",
    restaurant_name: "Clg Bites Biryani Nation",
    category: "Chicken Biryani",
    name: "Chicken Moghalai Biryani (Full)",
    description: "Rich Mughlai chicken biryani infused with saffron, egg shreds and creamy gravy.",
    price: 300,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1642821373181-696a54913e9a?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "cbn-chk-65-s",
    restaurant_id: "clg-bites-biryani-nation",
    restaurant_name: "Clg Bites Biryani Nation",
    category: "Chicken Biryani",
    name: "Chicken 65 Biryani (Single)",
    description: "Spicy curry-leaf tempered Chicken 65 tossed over flavorful biryani rice.",
    price: 210,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "cbn-chk-65-f",
    restaurant_id: "clg-bites-biryani-nation",
    restaurant_name: "Clg Bites Biryani Nation",
    category: "Chicken Biryani",
    name: "Chicken 65 Biryani (Full)",
    description: "Large serving of spicy South Indian Chicken 65 combined with fragrant basmati biryani.",
    price: 290,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "cbn-chk-mix-s",
    restaurant_id: "clg-bites-biryani-nation",
    restaurant_name: "Clg Bites Biryani Nation",
    category: "Chicken Biryani",
    name: "All Mix Chicken Biryani (Single)",
    description: "Chef special combination of Dum, Fry, and 65 chicken pieces in one grand biryani.",
    price: 210,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "cbn-chk-mix-f",
    restaurant_id: "clg-bites-biryani-nation",
    restaurant_name: "Clg Bites Biryani Nation",
    category: "Chicken Biryani",
    name: "All Mix Chicken Biryani (Full)",
    description: "The ultimate chicken lover feast with assorted boneless, fry and dum cuts in rich biryani rice.",
    price: 280,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "cbn-egg-s",
    restaurant_id: "clg-bites-biryani-nation",
    restaurant_name: "Clg Bites Biryani Nation",
    category: "Chicken Biryani",
    name: "Egg Biryani (Single)",
    description: "Golden spiced boiled eggs served with aromatic basmati dum biryani rice & raita.",
    price: 170,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1599043513903-ecac48078953?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "cbn-egg-f",
    restaurant_id: "clg-bites-biryani-nation",
    restaurant_name: "Clg Bites Biryani Nation",
    category: "Chicken Biryani",
    name: "Egg Biryani (Full)",
    description: "Double boiled eggs roasted in Andhra masala served over full pot dum biryani rice.",
    price: 230,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1599043513903-ecac48078953?auto=format&fit=crop&w=600&q=80"
  },

  // Veg Biryani
  {
    id: "cbn-veg-dum-s",
    restaurant_id: "clg-bites-biryani-nation",
    restaurant_name: "Clg Bites Biryani Nation",
    category: "Veg Biryani",
    name: "Veg Dum Biryani (Single)",
    description: "Fresh garden vegetables, potatoes, beans & carrots layered in saffron dum basmati rice.",
    price: 150,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "cbn-veg-dum-f",
    restaurant_id: "clg-bites-biryani-nation",
    restaurant_name: "Clg Bites Biryani Nation",
    category: "Veg Biryani",
    name: "Veg Dum Biryani (Full)",
    description: "Family portion wholesome vegetable dum biryani served with creamy vegetable raita.",
    price: 220,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "cbn-pan-bir-s",
    restaurant_id: "clg-bites-biryani-nation",
    restaurant_name: "Clg Bites Biryani Nation",
    category: "Veg Biryani",
    name: "Paneer Biryani (Single)",
    description: "Soft fresh malai paneer cubes marinated in yogurt and spices layered with aromatic biryani.",
    price: 210,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "cbn-pan-bir-f",
    restaurant_id: "clg-bites-biryani-nation",
    restaurant_name: "Clg Bites Biryani Nation",
    category: "Veg Biryani",
    name: "Paneer Biryani (Full)",
    description: "Double paneer cubes simmered in biryani spices and layered with fragrant ghee rice.",
    price: 290,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "cbn-kaju-bir-s",
    restaurant_id: "clg-bites-biryani-nation",
    restaurant_name: "Clg Bites Biryani Nation",
    category: "Veg Biryani",
    name: "Cashew Biryani (Single)",
    description: "Roasted golden whole cashews (kaju) tossed in ghee masala and dum basmati rice.",
    price: 220,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "cbn-kaju-bir-f",
    restaurant_id: "clg-bites-biryani-nation",
    restaurant_name: "Clg Bites Biryani Nation",
    category: "Veg Biryani",
    name: "Cashew Biryani (Full)",
    description: "Royal treat loaded with crunchy roasted cashews cooked in rich Hyderabadi biryani spices.",
    price: 300,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "cbn-kaju-pan-s",
    restaurant_id: "clg-bites-biryani-nation",
    restaurant_name: "Clg Bites Biryani Nation",
    category: "Veg Biryani",
    name: "Cashew & Paneer Mixed Biryani (Single)",
    description: "Delicious combination of roasted whole cashews and tender fresh paneer in spicy biryani.",
    price: 240,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "cbn-kaju-pan-f",
    restaurant_id: "clg-bites-biryani-nation",
    restaurant_name: "Clg Bites Biryani Nation",
    category: "Veg Biryani",
    name: "Cashew & Paneer Mixed Biryani (Full)",
    description: "Deluxe vegetarian feast loaded with premium kaju nuts and melt-in-mouth paneer cubes.",
    price: 300,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?auto=format&fit=crop&w=600&q=80"
  },

  // =========================================================================
  // 2. LOCAL HOME KITCHEN (Fast Food & Biryani's — Complete Authentic Menu)
  // =========================================================================

  // Biryani's
  {
    id: "lhk-bir-chk-dum",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Biryani's",
    name: "Chicken Dum Biryani",
    description: "Authentic Neerukonda homestyle chicken dum biryani cooked in sealed handi.",
    price: 170,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-bir-chk-fry",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Biryani's",
    name: "Chicken Fry Biryani",
    description: "Spicy crisp Andhra fried chicken placed over long grain flavored biryani rice.",
    price: 190,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-bir-chk-bone",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Biryani's",
    name: "Chicken Boneless Biryani",
    description: "Juicy boneless chicken pieces sauteed in thick gravy layered with hot dum rice.",
    price: 240,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-bir-chk-65",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Biryani's",
    name: "Chicken 65 Biryani",
    description: "Special spicy Chicken 65 pieces served atop aromatic masala biryani.",
    price: 250,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-bir-chk-lol",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Biryani's",
    name: "Chicken Lollipop Biryani",
    description: "Golden fried chicken drumettes tossed in spices over fragrant biryani rice.",
    price: 250,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-bir-chk-maju",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Biryani's",
    name: "Chicken Majubai Biryani",
    description: "Signature kitchen special chicken recipe with rich aromatic secret masala.",
    price: 250,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-bir-mush",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Biryani's",
    name: "Mushroom Biryani",
    description: "Button mushrooms sauteed in ground spices and layered in basmati rice.",
    price: 220,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-bir-kaju-mush",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Biryani's",
    name: "Kaju Mushroom Biryani",
    description: "Crunchy cashews and fresh mushrooms tossed together in rich fragrant biryani.",
    price: 250,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-bir-pan",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Biryani's",
    name: "Paneer Biryani",
    description: "Diced tender paneer tossed in roasted masala with long-grain basmati.",
    price: 220,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-bir-kaju-pan",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Biryani's",
    name: "Kaju Paneer Biryani",
    description: "Whole roasted cashews and cottage cheese cubes in spiced ghee biryani.",
    price: 260,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?auto=format&fit=crop&w=600&q=80"
  },

  // Starters - Veg
  {
    id: "lhk-stv-manch",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Starters - Veg",
    name: "Veg Manchurian",
    description: "Crisp fried vegetable balls tossed in wok-style ginger, garlic & soy glaze.",
    price: 80,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-stv-pan-manch",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Starters - Veg",
    name: "Paneer Manchuria",
    description: "Crispy paneer cubes tossed in zesty Indo-Chinese Manchurian sauce.",
    price: 180,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-stv-pan-maj",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Starters - Veg",
    name: "Paneer Majestic",
    description: "Stir fried paneer strips in spicy yogurt-mint sauce with curry leaves & green chillies.",
    price: 200,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-stv-kaju-pan-manch",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Starters - Veg",
    name: "Kaju Paneer Manchuria",
    description: "Golden roasted cashews and paneer tossed together in spicy Manchurian gravy.",
    price: 210,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-stv-mush-manch",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Starters - Veg",
    name: "Mushroom Manchuria",
    description: "Crisp battered button mushrooms glazed in tangy chili-garlic Manchurian sauce.",
    price: 180,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-stv-kaju-mush-manch",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Starters - Veg",
    name: "Kaju Mushroom Manchuria",
    description: "Wholesome cashews and juicy mushrooms stir-fried in rich Indo-Chinese spices.",
    price: 210,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?auto=format&fit=crop&w=600&q=80"
  },

  // Starters - Chicken
  {
    id: "lhk-stc-chk-manch",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Starters - Chicken",
    name: "Chicken Manchuria",
    description: "Boneless chicken pieces tossed with bell peppers, spring onions & soy glaze.",
    price: 180,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-stc-chk-65",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Starters - Chicken",
    name: "Chicken 65",
    description: "Classic deep-fried marinated chicken bites with curry leaves, yogurt and red chillies.",
    price: 200,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-stc-chilli-chk",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Starters - Chicken",
    name: "Chilli Chicken",
    description: "Spicy battered chicken wok-tossed with green chillies, garlic and capsicum.",
    price: 200,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-stc-kaju-chk-manch",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Starters - Chicken",
    name: "Chicken Kaju Manchuria",
    description: "Tender chicken and crunchy cashew nuts tossed in flavorful Manchurian sauce.",
    price: 210,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-stc-chk-maj",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Starters - Chicken",
    name: "Chicken Majestic",
    description: "Hyderabadi spiced chicken strips stir-fried with curd, mint, and crushed spices.",
    price: 220,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-stc-kaju-chilli-chk",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Starters - Chicken",
    name: "Kaju Chilli Chicken",
    description: "Whole roasted kaju nuts and spicy chilli chicken bites tossed in hot wok.",
    price: 230,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-stc-pep-chk",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Starters - Chicken",
    name: "Pepper Chicken",
    description: "Freshly ground black pepper chicken dry roast with curry leaves and onions.",
    price: 230,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-stc-lem-chk",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Starters - Chicken",
    name: "Lemon Chicken",
    description: "Tangy and zesty chicken morsels with fresh lemon reduction and herbs.",
    price: 230,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-stc-chk-lol",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Starters - Chicken",
    name: "Chicken Lollipop (6pcs)",
    description: "6 pieces of succulent chicken lollipops fried golden and served with spicy schezwan dip.",
    price: 250,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1608039829572-78524f79c4c7?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-stc-kfc-chk-lol",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Starters - Chicken",
    name: "KFC Chicken Lollipop",
    description: "Extra crunchy American crust coated chicken drumettes with secret spice blend.",
    price: 300,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1608039829572-78524f79c4c7?auto=format&fit=crop&w=600&q=80"
  },

  // Fried Rice
  {
    id: "lhk-fr-chk",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Fried Rice",
    name: "Chicken Fried Rice",
    description: "Classic wok-tossed basmati rice with seasoned chicken bits and scrambled egg.",
    price: 120,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-fr-chk-w",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Fried Rice",
    name: "Chicken Fried Rice (white)",
    description: "Non-spicy white pepper chicken fried rice stir-fried with scallions.",
    price: 130,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-fr-db-egg-chk",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Fried Rice",
    name: "Double Egg Chicken Fried Rice",
    description: "Loaded with double eggs and juicy chicken pieces stir-fried at high heat.",
    price: 130,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-fr-kaju-chk",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Fried Rice",
    name: "Kaju Chicken Fried Rice",
    description: "Premium fried rice with generous roasted cashews and shredded chicken.",
    price: 160,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-fr-veg",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Fried Rice",
    name: "Veg Fried Rice",
    description: "Stir-fried rice with fine chopped carrots, beans, cabbage and spring onions.",
    price: 80,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-fr-veg-w",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Fried Rice",
    name: "Veg Fried Rice (white)",
    description: "Mild aromatic white stir-fried rice with fresh diced vegetables.",
    price: 90,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-fr-db-egg",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Fried Rice",
    name: "Double Egg Fried Rice",
    description: "Rich scrambled double egg fried rice with freshly ground black pepper.",
    price: 110,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-fr-veg-manch",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Fried Rice",
    name: "Veg Manchurian Rice",
    description: "Wok tossed fried rice combined with crunchy vegetable Manchurian balls.",
    price: 110,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-fr-db-egg-manch",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Fried Rice",
    name: "Double Egg Manchuria Rice",
    description: "Double egg stir-fried rice topped with savory Manchurian gravy and bites.",
    price: 120,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-fr-veg-manch-w",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Fried Rice",
    name: "Veg Manchuria Rice (white)",
    description: "White pepper fried rice served with delicate vegetable Manchurian.",
    price: 120,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80"
  },

  // Noodles
  {
    id: "lhk-nd-chk",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Noodles",
    name: "Chicken Noodles",
    description: "Wok tossed Hakka noodles with chicken slices, egg and crunchy vegetables.",
    price: 120,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-nd-chk-w",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Noodles",
    name: "Chicken Noodles (white)",
    description: "Mild garlic white noodles tossed with tender chicken shreds.",
    price: 130,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-nd-db-egg-chk",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Noodles",
    name: "Double Egg Chicken Noodles",
    description: "Double egg scrambled into piping hot chicken noodles with chili oil.",
    price: 130,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-nd-kaju-chk",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Noodles",
    name: "Kaju Chicken Noodles",
    description: "Special noodles stir-fried with roasted cashews and juicy chicken.",
    price: 160,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-nd-veg",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Noodles",
    name: "Veg Noodles",
    description: "Street-style Hakka noodles stir-fried with julienned vegetables.",
    price: 80,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-nd-veg-w",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Noodles",
    name: "Veg Noodles (white)",
    description: "Delicate white butter garlic noodles with fresh seasonal veggies.",
    price: 90,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-nd-egg-manch",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Noodles",
    name: "Egg Manchurian Noodles",
    description: "Egg tossed noodles served with flavorful Manchurian sauce.",
    price: 120,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-nd-db-egg-manch",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Noodles",
    name: "Double Egg Manchurian Noodles",
    description: "Hearty double egg noodles with rich Manchurian dumplings & gravy.",
    price: 120,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-nd-veg-manch",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Noodles",
    name: "Veg Manchurian Noodles",
    description: "Vegetable noodles combined with golden crispy veg Manchurian.",
    price: 110,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-nd-kaju",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Noodles",
    name: "Kaju Noodles",
    description: "Vegetarian noodles loaded with roasted crunchy whole cashews.",
    price: 120,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-nd-kaju-manch",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Noodles",
    name: "Kaju Manchuria Noodles",
    description: "Delicious combo of roasted cashews, Manchurian balls and noodles.",
    price: 140,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80"
  },

  // Paneer & Mushroom Items
  {
    id: "lhk-pm-pan-fr",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Paneer & Mushroom",
    name: "Paneer Fried Rice",
    description: "Fried rice tossed with marinated soft paneer cubes & spices.",
    price: 150,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-pm-pan-nd",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Paneer & Mushroom",
    name: "Paneer Noodles",
    description: "Wok-fried noodles with generous cubes of fresh paneer.",
    price: 150,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-pm-mush-fr",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Paneer & Mushroom",
    name: "Mushroom Fried Rice",
    description: "Fresh button mushrooms stir-fried with fragrant basmati rice.",
    price: 150,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-pm-mush-nd",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Paneer & Mushroom",
    name: "Mushroom Noodles",
    description: "Savory sliced mushrooms wok-tossed with Hakka noodles.",
    price: 150,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80"
  },

  // Schezwan Items
  {
    id: "lhk-scz-veg-fr",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Schezwan Specials",
    name: "Veg Schezwan Fried Rice",
    description: "Fiery red Schezwan chili paste wok-fried with vegetables and rice.",
    price: 120,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1617093727343-374698b1b08d?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-scz-egg-fr",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Schezwan Specials",
    name: "Egg Schezwan Fried Rice",
    description: "Spicy Schezwan fried rice with scrambled egg and spring onions.",
    price: 140,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1617093727343-374698b1b08d?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-scz-manch-fr",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Schezwan Specials",
    name: "Manchurian Schezwan Fried Rice",
    description: "Tangy spicy Schezwan rice with crispy Manchurian bites.",
    price: 160,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1617093727343-374698b1b08d?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-scz-chk-fr",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Schezwan Specials",
    name: "Schezwan Chicken Fried Rice",
    description: "Tender chicken shreds tossed in hot red Schezwan sauce with basmati.",
    price: 170,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1617093727343-374698b1b08d?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-scz-veg-nd",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Schezwan Specials",
    name: "Veg Schezwan Noodles",
    description: "Zesty spicy noodles with stir-fried cabbage, carrots and peppers.",
    price: 120,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-scz-egg-nd",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Schezwan Specials",
    name: "Egg Schezwan Noodles",
    description: "Scrambled egg noodles tossed in bold Schezwan sauce.",
    price: 140,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-scz-manch-nd",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Schezwan Specials",
    name: "Manchurian Schezwan Noodles",
    description: "Crispy Manchurian balls stirred into spicy Schezwan noodles.",
    price: 160,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-scz-chk-nd",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Schezwan Specials",
    name: "Schezwan Chicken Noodles",
    description: "Hot Schezwan chili noodles loaded with spicy chicken chunks.",
    price: 170,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=600&q=80"
  },

  // SP Special Items
  {
    id: "lhk-sp-chk-fr",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "SP Items (Special)",
    name: "SP Chicken Fried Rice",
    description: "Chef's special double-spiced chicken fried rice with secret campus blend.",
    price: 140,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-sp-chk-nd",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "SP Items (Special)",
    name: "SP Chicken Noodles",
    description: "Special recipe wok noodles loaded with extra chicken and spices.",
    price: 140,
    is_veg: false,
    image_url: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-sp-pan-fr",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "SP Items (Special)",
    name: "SP Paneer Fried Rice",
    description: "Special paneer fried rice with roasted dry spices and extra paneer.",
    price: 180,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-sp-pan-nd",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "SP Items (Special)",
    name: "SP Paneer Noodles",
    description: "Special paneer noodles tossed with butter, chillies and spring greens.",
    price: 180,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-sp-mush-fr",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "SP Items (Special)",
    name: "SP Mushroom Fried Rice",
    description: "Special butter-sauteed mushroom fried rice with crackled black pepper.",
    price: 180,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "lhk-sp-mush-nd",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "SP Items (Special)",
    name: "SP Mushroom Noodles",
    description: "Special Hakka noodles packed with flavorful mushrooms & spices.",
    price: 180,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80"
  },

  // Extras
  {
    id: "lhk-ext-drinks",
    restaurant_id: "local-home-kitchen",
    restaurant_name: "Local Home Kitchen",
    category: "Extras",
    name: "Soft Drinks (Chilled Can / Bottle)",
    description: "Refreshing cold drink (Thums Up, Coca Cola, Sprite, or Fanta).",
    price: 40,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "cbn-ext-drinks",
    restaurant_id: "clg-bites-biryani-nation",
    restaurant_name: "Clg Bites Biryani Nation",
    category: "Extras",
    name: "Soft Drinks (Chilled Can / Bottle)",
    description: "Ice-cold refreshing soft drink to pair with your hot biryani.",
    price: 40,
    is_veg: true,
    image_url: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80"
  },

  // =========================================================================
  // 3. VILASA CAFÉ (Authentic Campus Menu)
  // =========================================================================

  {
    "id": "vc-vs-veg-manchuria",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Veg Starters",
    "name": "Veg Manchuria",
    "description": "Crispy fried mixed vegetable dumplings tossed in tangy Chinese garlic manchurian sauce.",
    "price": 120,
    "is_veg": true,
    "image_url": "https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-vs-paneer-manchuria",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Veg Starters",
    "name": "Paneer Manchuria",
    "description": "Golden paneer cubes tossed in rich ginger-garlic manchurian glaze with green onions.",
    "price": 210,
    "is_veg": true,
    "image_url": "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-vs-paneer-chilli",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Veg Starters",
    "name": "Paneer Chilli",
    "description": "Wok-tossed paneer cubes with crunchy bell peppers, diced onions and dark soy-chilli gravy.",
    "price": 240,
    "is_veg": true,
    "image_url": "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-vs-paneer-65",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Veg Starters",
    "name": "Paneer 65",
    "description": "Spicy South Indian style deep-fried paneer tempered with curry leaves, mustard seeds & yogurt.",
    "price": 240,
    "is_veg": true,
    "image_url": "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-vs-paneer-majestic",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Veg Starters",
    "name": "Paneer Majestic",
    "description": "Royal Hyderabadi paneer strips sauteed with mint, coriander, curd, and mild aromatic spices.",
    "price": 260,
    "is_veg": true,
    "image_url": "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-es-egg-manchuria",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Egg Starters",
    "name": "Egg Manchuria",
    "description": "Crispy battered hard-boiled egg chunks tossed in savory garlic and soy manchurian sauce.",
    "price": 130,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-es-double-egg-manchuria",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Egg Starters",
    "name": "Double Egg Manchuria",
    "description": "Extra portion of crispy egg bites smothered in zesty scallion manchurian gravy.",
    "price": 150,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-es-egg-chilli",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Egg Starters",
    "name": "Egg Chilli",
    "description": "Egg pieces stir-fried with hot green chillies, capsicum, and oriental sauces.",
    "price": 220,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-es-egg-65",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Egg Starters",
    "name": "Egg 65",
    "description": "Crunchy fried egg bites tossed in classic spicy curd tempering with crispy curry leaves.",
    "price": 220,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-es-omlet",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Egg Starters",
    "name": "Omlet",
    "description": "Classic pan-fried fluffy 2-egg omelette loaded with diced onions, green chillies and black pepper.",
    "price": 80,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nvs-guntur-chilli-chk",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Non-Veg Starters",
    "name": "Guntur Chilli Chicken (Bone)",
    "description": "Fiery Andhra style bone-in chicken braised with spicy Guntur red chillies and roasted spices.",
    "price": 190,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nvs-chk-manchuria",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Non-Veg Starters",
    "name": "Chicken Manchuria",
    "description": "Crispy chicken meatballs sauteed with garlic, ginger, green chillies and soy sauce.",
    "price": 210,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nvs-chilli-chk",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Non-Veg Starters",
    "name": "Chilli Chicken",
    "description": "Classic Indo-Chinese diced chicken tossed with crunchy onions, capsicum & spicy chilli sauce.",
    "price": 210,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nvs-chk-65",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Non-Veg Starters",
    "name": "Chicken 65",
    "description": "All-time favorite spicy deep-fried chicken cubes tossed with curry leaves, yogurt & green chillies.",
    "price": 210,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1610057099431-d73a1c9d2f2f?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nvs-garlic-chk",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Non-Veg Starters",
    "name": "Garlic Chicken",
    "description": "Tender chicken pieces glazed with aromatic roasted garlic, scallions and cracked peppercorn.",
    "price": 250,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nvs-chk-majestic",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Non-Veg Starters",
    "name": "Chicken Majestic",
    "description": "Dry and crispy chicken strips infused with mint, buttermilk tempering, and Andhra spices.",
    "price": 250,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nvs-dragon-chk",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Non-Veg Starters",
    "name": "Dragon Chicken",
    "description": "Batter-coated chicken strips tossed in a fiery red sweet & spicy sauce topped with roasted cashews.",
    "price": 260,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nvs-redhot-chk",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Non-Veg Starters",
    "name": "Redhot Chicken",
    "description": "Extremely spicy chicken cubes glazed with crushed red pepper reduction and hot garlic paste.",
    "price": 260,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nvs-pepper-chk",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Non-Veg Starters",
    "name": "Pepper Chicken",
    "description": "Succulent chicken morsels heavily seasoned with freshly ground black pepper and curry leaves.",
    "price": 260,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nvs-loose-chk",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Non-Veg Starters",
    "name": "Loose Chicken",
    "description": "Crispy shredded chicken bites stir-fried with shredded ginger, garlic, and hot red chillies.",
    "price": 260,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nvs-chk-555",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Non-Veg Starters",
    "name": "Chicken 555",
    "description": "Signature crispy chicken fingers tossed with zesty chilli paste, cashew bits, and curd glaze.",
    "price": 300,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nvs-kaju-chk",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Non-Veg Starters",
    "name": "Kaju Chicken",
    "description": "Tender chicken cooked with a generous mountain of roasted whole cashew nuts in royal masala.",
    "price": 300,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nvs-drums-heaven",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Non-Veg Starters",
    "name": "Drums of Heaven (6 Pieces)",
    "description": "6 juicy chicken drumettes frenched, deep-fried, and tossed in luscious spicy Schezwan glaze.",
    "price": 300,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1527477378399-52e6945a0b77?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nvs-chk-lollipop-6",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Non-Veg Starters",
    "name": "Chicken Lollipop (6 Pieces)",
    "description": "6 classic crispy fried chicken wings shaped into lollipops, served with homemade Schezwan dip.",
    "price": 300,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1527477378399-52e6945a0b77?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nvs-chk-wings-6",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Non-Veg Starters",
    "name": "Chicken Wings (6 Pieces)",
    "description": "6 golden spiced crispy chicken wings seasoned with house spice rub.",
    "price": 300,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1527477378399-52e6945a0b77?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nvs-chk-lollipop-3",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Non-Veg Starters",
    "name": "Chicken Lollipop (3 Pieces)",
    "description": "3 crunchy chicken lollipops paired with hot garlic dipping sauce.",
    "price": 180,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1527477378399-52e6945a0b77?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-vb-veg-biryani",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Veg Biryanis",
    "name": "Veg Biryani",
    "description": "Fragrant basmati rice layered with garden vegetables, mint, caramelized onions, and whole spices.",
    "price": 170,
    "is_veg": true,
    "image_url": "https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-vb-kaju-biryani",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Veg Biryanis",
    "name": "Kaju Biryani",
    "description": "Rich biryani loaded with premium roasted whole cashew nuts in fragrant saffron rice.",
    "price": 240,
    "is_veg": true,
    "image_url": "https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-vb-paneer-biryani",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Veg Biryanis",
    "name": "Paneer Biryani",
    "description": "Soft marinated paneer chunks layered with aromatic long-grain basmati biryani.",
    "price": 220,
    "is_veg": true,
    "image_url": "https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-vb-egg-biryani",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Veg Biryanis",
    "name": "Egg Biryani",
    "description": "Spiced boiled eggs cooked in flavorful dum gravy, layered with ghee-seasoned biryani rice.",
    "price": 170,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nvb-chk-dum-biryani",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Non-Veg Biryanis",
    "name": "Chicken Dum Biryani",
    "description": "Traditional slow dum-cooked Hyderabadi chicken biryani with tender meat, saffron & basmati rice.",
    "price": 190,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nvb-chk-curry-biryani",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Non-Veg Biryanis",
    "name": "Chicken Curry Biryani",
    "description": "Savory chicken curry layered with rich spiced basmati biryani for extra sauce lovers.",
    "price": 210,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nvb-chk-fry-biryani",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Non-Veg Biryanis",
    "name": "Chicken Fry Biryani",
    "description": "Andhra special spicy roast chicken fry pieces served on top of aromatic dum biryani rice.",
    "price": 210,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nvb-chk-65-biryani",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Non-Veg Biryanis",
    "name": "Chicken 65 Biryani",
    "description": "Crispy spicy Chicken 65 pieces tossed with curry leaf glaze over fragrant dum biryani.",
    "price": 270,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1610057099431-d73a1c9d2f2f?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nvb-chk-boneless-biryani",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Non-Veg Biryanis",
    "name": "Chicken Boneless Biryani",
    "description": "Juicy, boneless chicken cubes marinated in special tandoori masala atop fluffy biryani rice.",
    "price": 280,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nvb-chk-moglai-biryani",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Non-Veg Biryanis",
    "name": "Chicken Moglai Biryani",
    "description": "Decadent Mughlai style biryani infused with beaten egg, nuts, cream and fragrant herbs.",
    "price": 280,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nvb-chk-lollipop-biryani",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Non-Veg Biryanis",
    "name": "Chicken Lollipop Biryani (4-PC)",
    "description": "4 succulent fried chicken lollipops served on a generous portion of aromatic biryani rice.",
    "price": 300,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1527477378399-52e6945a0b77?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nvb-chk-wings-biryani",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Non-Veg Biryanis",
    "name": "Chicken Wings Biryani (4-PC)",
    "description": "4 flavorful seasoned chicken wings nestled inside steaming hot basmati biryani.",
    "price": 300,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1527477378399-52e6945a0b77?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nd-veg-noodles",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Noodles",
    "name": "Veg Noodles",
    "description": "Wok-tossed Hakka noodles with shredded cabbage, carrots, capsicum, and oriental sauces.",
    "price": 100,
    "is_veg": true,
    "image_url": "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nd-veg-manchurian-noodles",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Noodles",
    "name": "Veg Manchurian Noodles",
    "description": "Stir-fried noodles combined with crispy vegetable Manchurian balls in rich savory glaze.",
    "price": 130,
    "is_veg": true,
    "image_url": "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nd-sp-veg-noodles-kaju",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Noodles",
    "name": "Sp Veg Noodles (Kaju)",
    "description": "Special vegetable noodles packed with crunchy roasted cashew nuts and fresh vegetables.",
    "price": 150,
    "is_veg": true,
    "image_url": "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nd-egg-noodles",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Noodles",
    "name": "Egg Noodles",
    "description": "Egg-scrambled Hakka noodles tossed on high heat with crisp vegetables and soya sauce.",
    "price": 130,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nd-double-egg-noodles",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Noodles",
    "name": "Double Egg Noodles",
    "description": "Loaded with double the fluffy scrambled egg, stir-fried with noodles and spring onions.",
    "price": 140,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nd-sp-egg-noodles-kaju",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Noodles",
    "name": "Sp Egg Noodles (Kaju)",
    "description": "Special egg noodles loaded with roasted whole cashews and seasoned with chef's spices.",
    "price": 160,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nd-egg-manchurian-noodles",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Noodles",
    "name": "Egg Manchurian Noodles",
    "description": "Savory egg noodles tossed together with crispy seasoned egg Manchurian pieces.",
    "price": 140,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nd-sp-egg-manchurian-noodles",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Noodles",
    "name": "Sp Egg Manchurian Noodles",
    "description": "Deluxe egg noodles loaded with extra egg manchurian bites and zesty sauces.",
    "price": 160,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nd-chk-noodles",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Noodles",
    "name": "Chicken Noodles",
    "description": "Street-style wok-fried noodles with tender chicken strips, egg, and crunchy julienned veggies.",
    "price": 150,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nd-double-egg-chk-noodles",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Noodles",
    "name": "Double Egg Chicken Noodles",
    "description": "Hearty combo of double scrambled eggs and tender chicken bites stir-fried with noodles.",
    "price": 160,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nd-chk-manchurian-noodles",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Noodles",
    "name": "Chicken Manchurian Noodles",
    "description": "Savory noodles tossed with crunchy chicken Manchurian balls and spring onions.",
    "price": 170,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nd-paneer-noodles",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Noodles",
    "name": "Paneer Noodles",
    "description": "Soft paneer cubes wok-tossed with flavorful noodles, bell peppers and dark soy sauce.",
    "price": 160,
    "is_veg": true,
    "image_url": "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-fr-veg-fried-rice",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Fried Rice",
    "name": "Veg Fried Rice",
    "description": "Wok-tossed basmati rice with finely diced carrots, beans, cabbage, and light seasoning.",
    "price": 110,
    "is_veg": true,
    "image_url": "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-fr-veg-manchuria-fried-rice",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Fried Rice",
    "name": "Veg Manchuria Fried Rice",
    "description": "Classic vegetable fried rice tossed with crispy veg Manchurian dumplings.",
    "price": 130,
    "is_veg": true,
    "image_url": "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-fr-sp-veg-fried-rice",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Fried Rice",
    "name": "Sp Veg Fried Rice",
    "description": "Special vegetable fried rice with roasted cashew nuts and extra aromatic seasoning.",
    "price": 160,
    "is_veg": true,
    "image_url": "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-fr-veg-schezwan-fried-rice",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Fried Rice",
    "name": "Veg Schezwan Fried Rice",
    "description": "Spicy Schezwan sauce tossed fried rice with crunchy vegetables and fiery red chillies.",
    "price": 140,
    "is_veg": true,
    "image_url": "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-fr-sp-schezwan-fried-rice",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Fried Rice",
    "name": "Sp Schezwan Fried Rice",
    "description": "Extra spicy Schezwan fried rice with roasted cashew nuts and bell peppers.",
    "price": 180,
    "is_veg": true,
    "image_url": "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-fr-egg-fried-rice",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Fried Rice",
    "name": "Egg Fried Rice",
    "description": "Fluffy basmati rice wok-fried with scrambled eggs, diced vegetables and black pepper.",
    "price": 150,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-fr-sp-egg-fried-rice",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Fried Rice",
    "name": "Sp Egg Fried Rice",
    "description": "Chef's special egg fried rice with crunchy roasted cashews and aromatic herbs.",
    "price": 160,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-fr-egg-manchuria-rice",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Fried Rice",
    "name": "Egg Manchuria Rice",
    "description": "Savory fried rice blended with delicious egg Manchurian pieces.",
    "price": 140,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-fr-sp-egg-manchuria-rice",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Fried Rice",
    "name": "Sp Egg Manchuria Rice",
    "description": "Deluxe portion of egg Manchurian fried rice with rich scallion seasoning.",
    "price": 170,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-fr-chk-fried-rice",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Fried Rice",
    "name": "Chicken Fried Rice",
    "description": "Wok-charred fragrant basmati rice tossed with spiced chicken cubes, egg, and fresh veggies.",
    "price": 150,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-fr-chk-manchuria-fried-rice",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Fried Rice",
    "name": "Chicken Manchuria Fried Rice",
    "description": "Chicken fried rice loaded with crispy chicken Manchurian bites in garlic soy reduction.",
    "price": 180,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-fr-sp-chk-fried-rice",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Fried Rice",
    "name": "Sp Chicken Fried Rice",
    "description": "Special chicken fried rice with whole roasted cashews, egg, and signature seasoning.",
    "price": 180,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-fr-sp-chk-manchuria-rice",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Fried Rice",
    "name": "Sp Chicken Manchuria Rice",
    "description": "Grand portion of fried rice with chicken Manchurian balls, egg, and cashew nut garnish.",
    "price": 200,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-fr-paneer-fried-rice",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Fried Rice",
    "name": "Paneer Fried Rice",
    "description": "Golden paneer cubes tossed with steamed basmati rice, vegetables and light spices.",
    "price": 140,
    "is_veg": true,
    "image_url": "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-fr-schezwan-chk-fried-rice",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Fried Rice",
    "name": "Schezwan Chicken Fried Rice",
    "description": "Fiery Schezwan chicken fried rice with tender chicken, egg, and hot red chilli oil.",
    "price": 160,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-fr-sp-schezwan-chk-fried-rice",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Fried Rice",
    "name": "Sp Schezwan Chicken Fried Rice",
    "description": "Extra spicy Schezwan chicken rice with roasted whole cashews and crisp bell peppers.",
    "price": 200,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-fr-schezwan-paneer-fried-rice",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Fried Rice",
    "name": "Schezwan Paneer Fried Rice",
    "description": "Soft paneer cubes tossed in zesty spicy Schezwan sauce with aromatic basmati rice.",
    "price": 160,
    "is_veg": true,
    "image_url": "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-vc-paneer-butter-masala",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Veg Curries",
    "name": "Paneer Butter Masala",
    "description": "Soft paneer cubes simmered in a luscious, velvety tomato-butter gravy with aromatic kasuri methi.",
    "price": 210,
    "is_veg": true,
    "image_url": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-vc-methi-chaman",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Veg Curries",
    "name": "Methi Chaman",
    "description": "Kashmiri delicacy of paneer cooked in a rich, fragrant gravy of fresh fenugreek leaves and spices.",
    "price": 180,
    "is_veg": true,
    "image_url": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-vc-tomato-curry",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Veg Curries",
    "name": "Tomato Curry",
    "description": "Homestyle tangy and spiced ripe tomato gravy tempered with mustard, cumin and curry leaves.",
    "price": 120,
    "is_veg": true,
    "image_url": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-vc-kaju-tomato",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Veg Curries",
    "name": "Kaju Tomato",
    "description": "Whole roasted cashew nuts simmered in a creamy, tangy tomato and onion masala.",
    "price": 210,
    "is_veg": true,
    "image_url": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-vc-kadai-paneer",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Veg Curries",
    "name": "Kadai Paneer",
    "description": "Paneer cubes and crunchy bell peppers tossed in a robust gravy of freshly roasted kadai masala.",
    "price": 210,
    "is_veg": true,
    "image_url": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-vc-dal-tadka",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Veg Curries",
    "name": "Dal Tadka",
    "description": "Yellow lentils cooked to perfection and tempered with sizzling ghee, garlic, cumin & red chillies.",
    "price": 140,
    "is_veg": true,
    "image_url": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nvc-chk-curry-bone",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Non-Veg Curries",
    "name": "Chicken Curry (Bone)",
    "description": "Homestyle Andhra bone-in chicken curry simmered with spicy onion-ginger-garlic gravy.",
    "price": 200,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nvc-chk-curry-boneless",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Non-Veg Curries",
    "name": "Chicken Curry Boneless",
    "description": "Succulent boneless chicken pieces cooked in a rich, aromatic and spicy masala gravy.",
    "price": 300,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nvc-butter-chk",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Non-Veg Curries",
    "name": "Butter Chicken",
    "description": "Grilled chicken pieces bathed in a smooth, rich tomato, butter, and cream reduction.",
    "price": 300,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nvc-kadai-chk",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Non-Veg Curries",
    "name": "Kadai Chicken",
    "description": "Chicken and capsicum stir-fried in a spicy tomato gravy with freshly ground coriander and cumin.",
    "price": 280,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nvc-kolhapuri-chk",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Non-Veg Curries",
    "name": "Kolhapuri Chicken",
    "description": "Extremely spicy and rich chicken curry with coconut, sesame seeds and Kolhapuri red chillies.",
    "price": 280,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-nvc-kaju-chk-curry",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Non-Veg Curries",
    "name": "Kaju Chicken Curry",
    "description": "Royal chicken curry enriched with roasted cashews and velvety nut gravy.",
    "price": 320,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-bf-chapati-single",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Breads & Frankies",
    "name": "Chapati (Single)",
    "description": "Soft, freshly rolled whole wheat flatbread roasted on hot griddle.",
    "price": 25,
    "is_veg": true,
    "image_url": "https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-bf-chapati-full",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Breads & Frankies",
    "name": "Chapati Full",
    "description": "Set of warm, soft whole wheat chapatis perfect with any veg or non-veg curry.",
    "price": 50,
    "is_veg": true,
    "image_url": "https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-bf-parotta-single",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Breads & Frankies",
    "name": "Parotta (Single)",
    "description": "Flaky, layered South Indian Malabar parotta cooked golden with ghee.",
    "price": 60,
    "is_veg": true,
    "image_url": "https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-bf-parotta-full",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Breads & Frankies",
    "name": "Parotta Full",
    "description": "Pair of flaky layered parottas with crispy outer crust and soft interior.",
    "price": 90,
    "is_veg": true,
    "image_url": "https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-bf-roti",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Breads & Frankies",
    "name": "Roti",
    "description": "Tandoori style crisp and soft wheat bread.",
    "price": 20,
    "is_veg": true,
    "image_url": "https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-bf-paneer-frankie",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Breads & Frankies",
    "name": "Paneer Frankie",
    "description": "Warm roll stuffed with spicy masala paneer, sliced onions, chaat masala, and tangy sauces.",
    "price": 100,
    "is_veg": true,
    "image_url": "https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-bf-egg-roll",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Breads & Frankies",
    "name": "Egg Roll",
    "description": "Crisp parotta wrapped around an egg layer with crunchy onion relish and spicy chutneys.",
    "price": 85,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-bf-chk-frankie",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Breads & Frankies",
    "name": "Chicken Frankie",
    "description": "Delicious roll loaded with spiced juicy chicken chunks, pickled onions, and special mint sauce.",
    "price": 100,
    "is_veg": false,
    "image_url": "https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "vc-bf-veg-frankie",
    "restaurant_id": "vilasa-cafe",
    "restaurant_name": "Vilasa Café",
    "category": "Breads & Frankies",
    "name": "Veg Frankie",
    "description": "Classic veggie roll stuffed with spiced potato-veggie filling, onions and tangy sauces.",
    "price": 70,
    "is_veg": true,
    "image_url": "https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?auto=format&fit=crop&w=600&q=80"
  }
];
